name = "math_research"
version = "0.1.0"
defaultTargets = ["claims"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "67248ba34806c60bf24b5e99f0f09946ffc465c9"

[[lean_lib]]
name = "claims"
globs = ["claims.+"]
