"""Lossless claim metadata, generated Markdown, and graph-ready reference views.

Standard library only. This module does not assess mathematical correctness.
"""
import hashlib
import copy
import json
from pathlib import Path
import re
import subprocess
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / 'research/claims/index.json'
MARKDOWN = ROOT / 'research/CLAIM_INDEX.md'
SCHEMA = ROOT / 'research/claims/schema.json'
NOTICE = ('> **Automatically generated — do not edit this file, whether human or agent.**\n'
          '> Edit [claims/index.json](claims/index.json), then run '
          '`python3 tools/claim-index.py render` from the repository root.\n'
          '> Only the generator should modify this Markdown. '
          'See the [registry workflow](claims/README.md).\n\n')
HEADER = '| Label | Claim | Status | Full record |\n|---|---|---|---|\n'
TEXT_FIELDS = ('summary', 'assessment', 'record')
RELATIONS = ('cites', 'depends_on', 'refines', 'supersedes', 'corrects',
             'rediscovers', 'formalizes', 'applies', 'obstructs')


def require(ok, message):
    if not ok:
        raise ValueError(message)


def parse_json(text):
    def unique(pairs):
        result = {}
        for key, value in pairs:
            require(key not in result, f'Duplicate JSON key: {key}')
            result[key] = value
        return result
    return json.loads(text, object_pairs_hook=unique)


def read_json(path):
    return parse_json(Path(path).read_text())


def write_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n')


def shape(value, spec, path='$', schema=None):
    """Validate the deliberately small JSON-Schema vocabulary used by schema.json."""
    schema = spec if schema is None else schema
    if '$ref' in spec:
        target = schema
        for key in spec['$ref'].removeprefix('#/').split('/'):
            target = target[key]
        return shape(value, target, path, schema)
    types = {'object': dict, 'array': list, 'string': str, 'integer': int, 'null': type(None)}
    expected = spec.get('type')
    if expected:
        choices = expected if isinstance(expected, list) else [expected]
        require(any(type(value) is types[t] for t in choices), f'{path}: expected {expected}')
    if 'enum' in spec:
        require(value in spec['enum'], f'{path}: invalid value {value!r}')
    if isinstance(value, str):
        require(len(value) >= spec.get('minLength', 0), f'{path}: empty string')
        if 'pattern' in spec:
            require(re.fullmatch(spec['pattern'], value) is not None, f'{path}: invalid syntax')
    if isinstance(value, dict):
        props = spec.get('properties', {})
        require(set(spec.get('required', [])) <= value.keys(), f'{path}: missing required fields')
        if spec.get('additionalProperties') is False:
            require(value.keys() <= props.keys(), f'{path}: unknown fields {value.keys() - props.keys()}')
        for key, child in value.items():
            if key in props:
                shape(child, props[key], f'{path}.{key}', schema)
    if isinstance(value, list):
        if spec.get('uniqueItems'):
            require(len({json.dumps(v, sort_keys=True) for v in value}) == len(value),
                    f'{path}: duplicate items')
        for i, child in enumerate(value):
            if 'items' in spec:
                shape(child, spec['items'], f'{path}[{i}]', schema)


def markdown_links(text):
    """Inline links, including balanced parentheses/angle-bracket destinations.

    Reject unsupported link syntax rather than silently losing a destination.
    """
    result = []
    for match in re.finditer(r'(?<!!)\[([^\]\n]+)\]\(', text):
        start = match.end()
        end, depth = start, 1
        while end < len(text) and depth:
            if text[end] == '\\':
                end += 2
                continue
            if text[end] == '(':
                depth += 1
            elif text[end] == ')':
                depth -= 1
            if depth:
                end += 1
        require(depth == 0, 'Unclosed Markdown link')
        target = text[start:end]
        if target.startswith('<') and target.endswith('>'):
            target = target[1:-1]
        require(bool(target) and '\n' not in target, 'Empty/multiline link target')
        require(not re.search(r'\s+[\"\']', target), 'Link titles require explicit importer support')
        result.append({'label': match.group(1), 'target': target})
    require(len(result) == text.count(']('), 'Unsupported Markdown link syntax')
    return result


def references(claim):
    return [dict(link, field=field) for field in TEXT_FIELDS
            for link in markdown_links(claim[field])]


def validate(data):
    version = data.get('schema_version') if isinstance(data, dict) else None
    require(version in (1, 2), 'Unsupported claim schema version')
    shape(data, read_json(SCHEMA if version == 2 else SCHEMA.with_name('schema-v1.json')))
    ids = [c['id'] for c in data['claims']]
    require(len(ids) == len(set(ids)), 'Duplicate claim IDs')
    topics = [t['id'] for t in data.get('topic_definitions', [])]
    require(len(topics) == len(set(topics)), 'Duplicate topic IDs')
    for c in data['claims']:
        for field in TEXT_FIELDS:
            require('\n' not in c[field] and '\r' not in c[field], f"{c['id']}: multiline {field}")
        require(bool(markdown_links(c['record'])), f"{c['id']}: missing full-record link")
        references(c)
        f = c['formalization']
        if f['status'] in ('partial', 'complete'):
            require(bool(f['scope']) and bool(f['references']),
                    f"{c['id']}: verified coverage requires explicit scope and references")
        if version == 2:
            require(set(c['topics']) <= set(topics), f"{c['id']}: undefined topic")
            for field, review in c['reviews'].items():
                require(bool(review['evidence']), f"{c['id']}: review needs evidence")
                if review['state'] == 'pending':
                    require(bool(review['next_action']), f"{c['id']}: pending review needs next action")
                if review['state'] == 'reviewed' and field != 'relationships':
                    value = f['status'] if field == 'formalization' else c[field]
                    require(value is not None and value != [], f"{c['id']}: reviewed {field} is empty")
    edge_ids = set()
    for edge in data['relationships']:
        require(edge['id'] not in edge_ids, 'Duplicate relationship ID')
        edge_ids.add(edge['id'])
        for endpoint in ('source', 'target'):
            e = edge[endpoint]
            if e['namespace'] == 'current':
                require(e['id'] in ids, f"{edge['id']}: missing {endpoint} claim {e['id']}")
            else:
                require(bool(e['locator']), f"{edge['id']}: non-current endpoint needs a locator")
        if edge['review_status'] == 'reviewed':
            require(bool(edge['evidence']), f"{edge['id']}: reviewed edge needs evidence")
    decisions=data.get('dependency_decisions',[])
    require(len({d['candidate_id'] for d in decisions})==len(decisions),'Duplicate dependency candidate decision')
    for decision in decisions:
        if decision['state']=='accepted':
            require(decision['relation_id'] in edge_ids,'Accepted candidate has no recorded relationship')
    return data


def upgrade(data):
    """Lossless v1 -> v2 metadata expansion; no curation is inferred."""
    validate(data)
    if data['schema_version'] == 2:
        return copy.deepcopy(data)
    new = copy.deepcopy(data)
    new['schema_version'] = 2
    new['topic_definitions'] = []
    for claim in new['claims']:
        claim['reviews'] = {}
        claim['formalization']['artifacts'] = []
        if claim['significance'] is not None:
            claim['significance'] = {'category': 'unassessed', 'rationale': claim['significance'],
                'novelty': 'unknown', 'publication_status': 'unknown', 'references': [], 'next_action': None}
    for edge in new['relationships']:
        edge['scope'] = 'Migrated v1 relationship; scope review pending.'
        edge['review'] = None
    return validate(new)


def load(path=REGISTRY):
    return validate(read_json(path))


def legacy_rows(text):
    require(HEADER in text, 'Expected one four-column claim table')
    require(text.count(HEADER) == 1, 'Ambiguous table header')
    preamble, tail = text.split(HEADER)
    rows = []
    for number, line in enumerate(tail.splitlines(), len(preamble.splitlines()) + 3):
        if not line.strip():
            continue
        require(line.startswith('| `') and line.endswith(' |'), f'Line {number}: unparsed table content')
        # The audited legacy table uses space-pipe-space cell boundaries. Bare
        # math bars occur inside 22 cells and must not become extra columns.
        cells = line[2:-2].split(' | ')
        require(len(cells) == 4, f'Line {number}: ambiguous cell boundaries ({len(cells)})')
        require(re.fullmatch(r'`[^`]+`', cells[0]) is not None, f'Line {number}: malformed label')
        rows.append((number, cells[0][1:-1], *cells[1:]))
    require(bool(rows), 'Empty index')
    return preamble, rows


def import_markdown(text):
    preamble, rows = legacy_rows(text)
    data = {'schema_version': 1, 'preamble': preamble, 'claims': [], 'relationships': []}
    for _, label, summary, assessment, record in rows:
        data['claims'].append({'id': label, 'summary': summary, 'assessment': assessment,
                              'record': record, 'mathematical_status': None,
                              'formalization': {'status': None, 'scope': None, 'references': []},
                              'topics': [], 'significance': None})
    return validate(data)


def escape_cell(text):
    # GFM requires math bars to be escaped even inside inline code.
    return re.sub(r'(?<!\\)((?:\\\\)*)\|', r'\1\\|', text)


def render(data):
    validate(data)
    rows = ['| ' + ' | '.join(escape_cell(v) for v in
            ('`' + c['id'] + '`', c['summary'], c['assessment'], c['record'])) + ' |'
            for c in data['claims']]
    return NOTICE + data['preamble'] + HEADER + '\n'.join(rows) + '\n'


def reconcile(text, data, revision=None):
    _, rows = legacy_rows(text)
    require(len(rows) == len(data['claims']), 'Claim count changed')
    escaped = []
    links = 0
    for old, c in zip(rows, data['claims']):
        number, label, *cells = old
        require(label == c['id'], f'Claim order/ID changed at line {number}')
        require(cells == [c[f] for f in TEXT_FIELDS], f'{label}: original content changed')
        links += len(references(c))
        fields = [f for f in TEXT_FIELDS if escape_cell(c[f]) != c[f]]
        if fields:
            escaped.append({'id': label, 'line': number, 'fields': fields})
    return {'source_revision': revision, 'source_sha256': hashlib.sha256(text.encode()).hexdigest(),
            'claims': len(rows), 'claim_links': links, 'all_labels_fields_links_and_order_preserved': True,
            'rendering_only_pipe_escapes': escaped,
            'other_rendering_changes': ['generated-file notice', 'blank lines between table rows normalized'],
            'classification': 'Unreviewed; original assessment text retained verbatim',
            'inferred_relationships': 0, 'passed': True}


def local_target(target, root=ROOT):
    p = urlparse(target)
    if p.scheme in ('http', 'https'):
        if p.netloc in ('kbr.is-a.dev', 'kbr-.github.io') and p.path.rstrip('/') == '/math-research':
            return root / 'notebook.html', unquote(p.fragment)
        prefix = '/kbr-/math-research/blob/main/'
        if p.netloc == 'github.com' and p.path.startswith(prefix):
            return root / unquote(p.path[len(prefix):]), unquote(p.fragment)
        return None
    require(not p.scheme and not p.netloc, f'Unsupported link scheme: {target}')
    path = (root / 'research' / unquote(p.path or 'CLAIM_INDEX.md')).resolve()
    require(path.is_relative_to(root.resolve()), f'Link escapes the repository: {target}')
    return path, unquote(p.fragment)


def file_anchors(path):
    text = path.read_text()
    found = set(re.findall(r'\bid=[\"\']([^\"\']+)[\"\']', text))
    if path.suffix.lower() == '.md':
        used = {}
        for heading in re.findall(r'^#{1,6}\s+(.+?)\s*#*$', text, re.M):
            slug = re.sub(r'[^\w\- ]', '', re.sub(r'<[^>]+>', '', heading).lower()).replace(' ', '-')
            n = used.get(slug, 0)
            used[slug] = n + 1
            found.add(slug + (f'-{n}' if n else ''))
    return found


def check_targets(data, root=ROOT):
    refs = [(c['id'], r['target']) for c in data['claims'] for r in references(c)]
    refs += [(c['id'], t) for c in data['claims'] for t in c['formalization']['references']]
    for c in data['claims']:
        for artifact in c['formalization'].get('artifacts', []):
            refs += [(c['id'], t) for t in artifact['references']]
            if artifact['verification']:
                refs.append((c['id'], artifact['verification']))
        if isinstance(c['significance'], dict):
            refs += [(c['id'], t) for t in c['significance']['references']]
        for review in c.get('reviews', {}).values():
            refs += [(c['id'], e['target']) for e in review['evidence']]
    refs += [('preamble', r['target']) for r in markdown_links(data['preamble'])]
    for edge in data['relationships']:
        refs += [(edge['id'], x) for x in edge['evidence']]
        refs += [(edge['id'], e['locator']) for e in (edge['source'], edge['target'])
                 if e['namespace'] != 'current']
    errors, external, anchors = [], set(), {}
    for owner, target in refs:
        local = local_target(target, root)
        if local is None:
            external.add(target)
            continue
        path, fragment = local
        if not path.is_file():
            errors.append({'id': owner, 'target': target, 'error': 'missing local file'})
        elif fragment:
            if path not in anchors:
                anchors[path] = file_anchors(path)
            if fragment not in anchors[path]:
                errors.append({'id': owner, 'target': target, 'error': 'missing local anchor'})
    return {'references_checked': len(refs), 'external_targets_preserved_not_fetched': sorted(external),
            'errors': errors, 'passed': not errors}


def exported(data, claims=None):
    claims = data['claims'] if claims is None else claims
    return {'schema_version': data['schema_version'], 'reference_base': 'research/CLAIM_INDEX.md',
            'topic_definitions': data.get('topic_definitions', []),
            'claims': [dict(c, references=references(c)) for c in claims],
            'relationships': data['relationships'],
            'relationship_coverage': 'incomplete; absent edges do not establish independence'}
