-- Fixed controls for qualitative reconstruction shortcuts; no dimension series.
R=QQ[t,z];
modT=coker matrix{{t,z^3}};
modM=(coker matrix{{z}})++modT;
rr=res modM;
assert(numgens target gens modM==2);
assert(sort flatten degrees source rr.dd_1=={1,1,3});
assert(numcols basis modT==3);
fibreM=coker (presentation modM | t*id_(target presentation modM));
assert(numcols basis fibreM==4);
print("SCM control L=3: S-generators2 in weight0; S-relations1,1,3; torsion length3; t-fibre length4.");
A=QQ[t];
aModel=A^1 ++ coker matrix{{t,0,0},{0,t,0},{0,0,t}};
assert(rank aModel==1);
print("PID control: rank1 plus three t-torsion generators; weighted shifts0,1,2 give parameter relation maximum3.");
Q=QQ[a,b,c,d]/ideal(a^3,a*b,b^2,c^3,c*d,d^2);
socQ=annihilator ideal(a,b,c,d);
assert(numcols basis Q==16);
assert(numcols basis socQ==4);
assert(numcols basis(Q/ideal(a,b,c,d))==1);
print("Four-jump control: Q length16, socle4, top1; its dual has common dark space1 and generator space4.");
B=QQ[u];
qM=matrix{{0_B,1_B,0_B},{0_B,0_B,1_B},{0_B,0_B,0_B}};
idM=id_(B^3);
invM=idM+u*qM+u^2*qM^2;
assert((idM-u*qM)*invM==idM);
absorb=matrix{{0_B},{0_B},{1_B}};
hM=u*invM*absorb;
assert(hM_(0,0)==u^3);
print("Absorbing-chain control: exact path transform(u^3,u^2,u), despite absorption probability one.");
assert((1-u)*(1+u+u^2)==1-u^3);
assert(1-u^3!=1_B);
print("Perturbation control: truncating (1-u)^(-1) after degree2 leaves nonzero remainder-u^3.");
print("All fixed controls passed.");
