\\ Test the smallest nontrivial elliptic modification: n=4,d=2,N=12.
\\ Question: at one boundary point on a smooth curve, does its unique section
\\ have zeros as a rank-two bundle section? This tests which Atiyah case
\\ needs a general argument; it does not prove generic/all-degree behavior.
\\ Search at most 970 ordered parameter tuples over F_101, stopping at
\\ the first corank-one point with order exactly 12 and nontrivial determinant.
\\ Generate a Singular certificate for projective common zeros, with q0
\\ removed and handled separately in the modified local frame.
T='T; XX=['x0,'x1,'x2,'x3]; P=101; N=12;
mkrows(n,d,a,M)={
  my(W=vector(n,i,sqrt(1+a[i]*T+O(T^(M+1)))),out=List());
  for(mask=0,2^n-1,
    if(hammingweight(mask)>d,next);
    my(f=prod(i=1,n,if(bittest(mask,i-1),W[i],1)));
    for(q=0,(d-hammingweight(mask))\2,listput(out,[q,mask,f*T^q]));
  ); Vec(out)
};
cmat(rows,M)=matrix(#rows,M+1,i,j,polcoef(rows[i][3],j-1,T));
{
  my(a,rows,A,K,nextc,found=0,tried=0,control=0,baseD);
  for(a3=3,12,
    for(a4=4,100,
      if(a4==a3,next);
      a=vector(4,i,Mod([1,2,a3,a4][i],P)); tried++;
      rows=mkrows(4,2,a,N); A=cmat(rows,N-1);
      if(matrank(A)==N,
        if(!control,print("Full-rank control: a=",liftall(a)); control=1);
        next;
      );
      K=matker(A~);
      if(matsize(K)[2]!=1,next);
      if(matrank(cmat(rows,N-2))!=N-1,next);
      nextc=sum(i=1,N,K[i,1]*polcoef(rows[i][3],N,T));
      if(!nextc,next);
      baseD=matdet(cmat(mkrows(3,3,a,N-1),N-1));
      if(!baseD,next);
      found=1; break;
    );
    if(found,break);
  );
  if(!found,error("no suitable point in bounded search; do not enlarge without review"));
  if(!control,
    for(b4=4,100,
      if(Mod(b4,P)==a[3],next);
      my(ac=a); ac[4]=Mod(b4,P);
      if(matrank(cmat(mkrows(4,2,ac,N),N-1))==N,
        print("Full-rank control: a=",liftall(ac)); control=1; break;
      );
    );
    if(!control,error("no full-rank negative control in bounded line"));
  );
  if(A~*K!=matrix(N,1),error("left-kernel certificate invalid"));
  my(U=0,V=0,x0=XX[1],x1=XX[2],x2=XX[3],x3=XX[4],homT=(x1^2-x0^2)/a[1]);
  for(i=1,N,
    my(q=rows[i][1],mask=rows[i][2],eps=bittest(mask,3),rwt=hammingweight(bitand(mask,7)),
       f=homT^q*prod(j=1,3,if(bittest(mask,j-1),XX[j+1],1))*x0^(2-eps-2*q-rwt));
    if(eps,V+=K[i,1]*f,U+=K[i,1]*f);
  );
  my(W=vector(4,i,sqrt(1+a[i]*T+O(T^(N+1)))),
     uf=substvec(U,XX,[1,W[1],W[2],W[3]]),
     vf=substvec(V,XX,[1,W[1],W[2],W[3]]),f=uf+vf*W[4]);
  if(valuation(f,T)!=N || polcoef(f,N,T)!=nextc,error("homogenization/branch jet mismatch"));
  print("Chosen parameters: ",liftall(a),"; tuples examined: ",tried);
  print("Ranks of 12x11,12x12,12x13 jets: ",[matrank(cmat(rows,10)),matrank(A),matrank(cmat(rows,12))]);
  print("Basis rows [q,mask]: ",vector(N,i,[rows[i][1],rows[i][2]]));
  print("Left-kernel coefficients: ",liftall(K));
  print("Order-12 coefficient: ",nextc,"; base Delta_(3,3): ",baseD);
  print("U (degree 2) = ",liftall(U)); print("V (degree 1) = ",liftall(V));
  print("At q0 the modified first component is nonzero; det F=eta^3 is nontrivial by base determinant.");
  my(out="research/results/cube-elliptic-modification-20260926/common-zero-certificate.sing");
  write(out,"// Generated by bmd_cube_elliptic_section_probe.gp; exact finite-field certificate.");
  write(out,"LIB \"elim.lib\"; ring R=101,(x0,x1,x2,x3),dp;");
  write(out,"poly U=",liftall(U),"; poly V=",liftall(V),";");
  write(out,"poly Q2=",liftall(a[1]*x2^2-a[2]*x1^2+(a[2]-a[1])*x0^2),";");
  write(out,"poly Q3=",liftall(a[1]*x3^2-a[3]*x1^2+(a[3]-a[1])*x0^2),";");
  write(out,"ideal point=x1-x0,x2-x0,x3-x0;");
  write(out,"ideal J=Q2,Q3,U,V; J=sat(J,point)[1]; J=std(J);");
  write(out,"print(\"Dimension of affine cone of common zeros away from q0 (<=0 means no projective zeros):\"); dim(J);");
  write(out,"print(\"Groebner basis certificate:\"); J;");
  write(out,"ideal C=Q2,Q3,V*x0,V; C=sat(C,point)[1]; C=std(C);");
  write(out,"print(\"Positive control: force a shared factor; affine cone dimension must be 1:\"); dim(C);");
  write(out,"quit;");
  print("Saved ",out);
}
quit;
