\\ Symbolic kernel-block determinants D_T at k = 1 (cycle bmd-20261009-l, 9 October 2026).
\\ For M = 2, 3 and p = M - 1 (one kernel column), computes D_i(u) = det[standard negative columns | K_u(z^i)]
\\ in coefficient space, with symbolic roots y1..yM, and factors [u^(B+t)] D_i (D_i = P_Lambda / Vand^2 up to units) for i <= 3, t <= 3.
\\ Question: is [u^(B+t)] D_i in the ideal generated by the window's [u^(B+s)] D_0, s <= t (monomial minimality at
\\ k = 1)? Records the factorizations and the reduction of [u^(B+t)] D_i modulo that ideal (Groebner-free check:
\\ divisibility by the leading coefficient's square-free part is printed when it holds).
OUT = "research/results/bmd-20261009-l/monomial-symbolic.txt";
Zv = varhigher("zz");
c(n) = binomial(-3/2, n);
T1(F) = { my(d = poldegree(F, Zv)); sum(i = 0, d, polcoef(F, i, Zv) * c(i + 1) / c(i) * Zv^(i + 1)) };
{
  foreach([2, 3], M,
    my(Y = vector(M, s, eval(Str("y", s))), P = prod(s = 1, M, Zv - Y[s]), p = M - 1, k = 1, TT = 3);
    my(B = p * (p + 1) / 2 + p * (p - 1) / 2 + k, NU = B + TT, V = prod(a = 1, M, prod(b = a + 1, M, Y[b] - Y[a])));
    my(ncol = vector(p, n, my(r = lift(Mod(sum(m = 0, NU - n, c(m) * c(n + m) * 'u^(n + m) * Zv^m), P))); vector(M, s, polcoef(r, s - 1, Zv))));
    write(OUT, "M=", M, " p=", p, " B=", B);
    my(D0 = 0);
    for (i = 0, 3,
      my(F = P * Zv^i, col = vector(M));
      for (m = 1, NU, F = T1(F); my(r = lift(Mod(F, P))); for (s = 0, M - 1, col[s + 1] += c(m) * polcoef(r, s, Zv) * 'u^m));
      my(A = matrix(M, M, r, j, if(j <= p, ncol[j][r], col[r])), D = matdet(A));
      if(i == 0, D0 = D);
      for (t = 0, TT, my(cf = polcoef(D, B + t, 'u), q = cf);
        write(OUT, "  i=", i, " t=", t, ": [u^(B+t)] D_i = ", factor(q)))));
}
