-- Pre-stable thresholds l_0(d+1, m) on {0,1}^n from graded solution modules (entry-2026-09-26-cube-dimension-four).
--
-- Statement computed.  By the threshold-ideal lemma, l_0(h, m) is the initial degree of I^{(h)}_m = {W_m : W in
-- Sol^{(h)}_m}, where Sol^{(h)}_m = ker A_m, A_m having rows T^Q z^r (r in {0,1}^n, 2Q+|r| <= h-1) and columns
-- c = 0..m, entry = coefficient of T^c (rows built from w_i = sqrt(1+4 y_i T), which span the same module as the root
-- curve z_i = (1-w_i)/2 because the row set is closed under lowering r).  A homogeneous solution of excess l has
-- W_c of degree l + m - c, and its top coordinate W_m has degree l.  The ideal I is generated by the top coordinates of
-- any generating set, so l_0 = the least excess of a minimal generator with nonzero top coordinate.
--
-- For each (n, d, m) the script prints the number of minimal generators, the rank m+1-N (N = number of rows), their
-- excesses, the excess sum, and l_0.  Usage: set the list `jobs` of (n, d, mlo, mhi) and the field `kk` below.
Cj = j -> lift((product(toList(0..j-1), i -> (1/2 - i))) / (j!) * 4^j, ZZ);
kk = ZZ/32003;
-- line mode (second argument "line"): restrict to the line y = a u + b v for random a, b in kk^n (fixed seed), over
-- kk[u,v]; for a free global module and a generic line the minimal generator excesses and l_0 equal the global ones.
line = #scriptCommandLine > 2 and scriptCommandLine#2 == "line";
setRandomSeed 1;
run1 = (n, d, m) -> (
    t0 := cpuTime();
    R := if line then kk[u,v] else kk[y_1..y_n];
    ys := if line then apply(n, i -> random(kk) * R_0 + random(kk) * R_1) else apply(n, i -> R_i);
    S := R[T];
    ws := apply(n, i -> sum(toList(0..m), j -> (Cj j) * (sub(ys#i, S))^j * T^j));
    rows := flatten apply(toList(0..d//2), Q -> flatten apply(subsets(n), sub0 -> (
        if 2*Q + #sub0 <= d then {(Q, sub0)} else {})));
    A := matrix apply(rows, rw -> (
        f := T^(rw#0) * product(rw#1, i -> ws#i);
        apply(toList(0..m), cc -> sub(coefficient(T^cc, f + 0*T^(m+1)), R))));
    f0 := map(R^(apply(rows, rw -> -(rw#0))), R^(apply(toList(0..m), c -> -c)), A);
    assert isHomogeneous f0;
    -- optional third argument: excess limit L; syzygies are computed only up to excess L (degree m + L)
    K := if #scriptCommandLine > 3 then (
            G := syz(f0, DegreeLimit => m + value scriptCommandLine#3);
            G_(select(toList(0..numcols G - 1), j -> G_{j} != 0)))
         else mingens kernel f0;
    exc := apply(numcols K, j -> (
        col := K_{j};
        cc := first select(toList(0..m), c -> col_(c,0) != 0);
        first degree col_(cc,0) + cc - m));
    tops := select(toList(0..numcols K - 1), j -> K_(m,j) != 0);
    l0 := if #tops == 0 then infinity else min apply(tops, j -> exc#j);
    << (if line then "line " else "") << "n=" << n << " d=" << d << " m=" << m << " rows=" << #rows << " rank=" << m + 1 - #rows
       << " gens=" << numcols K << " excesses=" << toString sort exc << " sum=" << sum exc << " l0=" << l0 << " cpu=" << (cpuTime() - t0) << endl << flush;
    );
-- jobs: first argument "n,d,mlo,mhi/n,d,mlo,mhi/...".
jobs = (if #scriptCommandLine > 1 then apply(separate("/", scriptCommandLine#1), s -> toSequence apply(separate(",", s), value)) else {(3, 3, 12, 14), (4, 2, 12, 18)});
for jb in jobs do for m from jb#2 to jb#3 do run1(jb#0, jb#1, m);
exit 0;
