#!/usr/bin/env python3
"""Local lengths of the first-step forms at a two-pair point of a random plane (cycle bmd-20261009-kgv).

Reads a plane file of research/tools/bmd_plane_minors.cpp (cut or uncut: F = last minor, m1 = the one before it,
extraK, collisionForms = a_1..a_4, then a_i - a_k, i < k) and writes a Singular script that moves the two-pair point
of collision forms 0 and 9 (pairs {0,1}, {3,4} of the five points 0, a_1, ..., a_4) to the origin, in local
coordinates u, v = those two forms, and computes with a local ordering (ds) the local lengths at the point of
(F, m1), of the colon (F, m1) : k, and of F, m1 orders.  Statement tested (conj:cube-two-pair-colon-excess): the
colon's local length equals i(F, m1) - d^2 (d - 1)^2.  This script only rewrites text; Singular does the work.

Usage: bmd_two_pair_length.py PLANE.m2 P OUT.sing"""
import re
import sys

plane, p, out = sys.argv[1], sys.argv[2], sys.argv[3]
lines = open(plane).read().split('\n')
start = lines.index('minorList = {')
end = lines.index('};', start)
minors = [l.rstrip(',') for l in lines[start + 1:end] if l.strip() not in ('', '0', '0,')]
F, m1 = minors[-1], minors[-2]
k = next(l for l in lines if l.startswith('extraK = ')).split('=', 1)[1].strip().rstrip(';')
forms = re.search(r'collisionForms = \{(.*)\};', '\n'.join(lines)).group(1).split(',')
l1, l2 = forms[0].strip(), forms[9].strip()
with open(out, 'w') as f:
    f.write(f'''// generated by research/tools/bmd_two_pair_length.py from {plane}
ring r = {p}, (x, y), dp;
poly F = {F};
poly m1 = {m1};
poly k = {k};
poly l1 = {l1};
poly l2 = {l2};
// l = A (x, y)^T + c; local coordinates u = l1, v = l2: (x, y)^T = A^-1 ((u, v)^T - c)
matrix A[2][2] = jet(diff(l1, x), 0), jet(diff(l1, y), 0), jet(diff(l2, x), 0), jet(diff(l2, y), 0);
number c1 = number(jet(l1, 0)); number c2 = number(jet(l2, 0));
number dt = number(A[1,1] * A[2,2] - A[1,2] * A[2,1]);
ring s = {p}, (u, v), ds;
matrix A = imap(r, A);
number c1 = imap(r, c1); number c2 = imap(r, c2); number dt = imap(r, dt);
poly X = (A[2,2] * (u - c1) - A[1,2] * (v - c2)) / dt;
poly Y = (-A[2,1] * (u - c1) + A[1,1] * (v - c2)) / dt;
map phi = r, X, Y;
poly F = phi(F); poly m1 = phi(m1); poly k = phi(k);
"orders: F " + string(ord(F)) + ", m1 " + string(ord(m1)) + ", k " + string(ord(k));
ideal I = F, m1;
ideal SI = std(I);
"local length of (F, m1): " + string(vdim(SI));
ideal Q = quotient(SI, k);
"local length of (F, m1) : k: " + string(vdim(std(Q)));
quit;
''')
print('wrote', out)
