"""Base block m <= 7 of the four-element square conjecture, by exact algebra in Singular.

Statement tested.  Let S be a four-element F_2-subspace of a characteristic-2 field with c_1 != 0,
n = 2, m = k-l-1 <= 7.  By the coefficient formula, degree <= 6+4(k-1)-h is attainable with origin
order exactly l iff there are homogeneous w^(u) in F[y1,y2] of degree l+m-u (u = 0..m, w^(m) != 0)
with, for all 0 <= a,b <= 3, a+b <= h-1 and 0 <= t < floor((h+3-a-b)/4),
    sum_u w^(u) X_{ab,u-t} = 0,   X_{ab,r} = degree-r part of x(y1)^a x(y2)^b,
where after scaling x(y) = y + y^2 + B y^4 + O(y^8) with B = b_2 = 1 + c_0^2/c_1^3 (so B != 1), and
only r <= 7 occurs.  The conjecture says the largest attainable h is ceil(m/2) for every l.

For each m and each h in (ceil(m/2), ceil(m/2)+1) the script builds the condition matrix A over
F_2[B,y1,y2] (rows = conditions, columns u = 0..m) and runs Singular:
  * existence: a syzygy of A whose last component is exactly 1, printed as EXIST lines (its
    y-homogeneous part is a solution for l = 0, and y1^l times it gives every l, for every B);
  * nonexistence: a generator f e_m of the intersection of the row module of A with R e_m whose f
    is nonzero and free of B, printed as NONEX, with coefficients LAMBDA_r from lift() such that
    sum_r LAMBDA_r row_r = f e_m; then w^(m) = 0 for every solution and every B.
  NONE is printed if no such certificate is found.
Usage: bmd_four_base_block.py OUTDIR [MMAX]   (writes one .sing script and its output per case)
"""
import itertools, subprocess, sys
from pathlib import Path


def poly_mul(p, q):
    """Polynomials as dicts {(i, j, e): coeff mod 2} for y1^i y2^j B^e."""
    r = {}
    for (a, c) in p.items():
        for (b, d) in q.items():
            key = (a[0] + b[0], a[1] + b[1], a[2] + b[2])
            r[key] = (r.get(key, 0) + c * d) % 2
    return {k: v for k, v in r.items() if v}


def xpow(var, a):
    """(y + y^2 + B y^4)^a in variable var (0 or 1), truncated at degree 7."""
    x = {((1, 0, 0) if var == 0 else (0, 1, 0)): 1,
         ((2, 0, 0) if var == 0 else (0, 2, 0)): 1,
         ((4, 0, 1) if var == 0 else (0, 4, 1)): 1}
    p = {(0, 0, 0): 1}
    for _ in range(a):
        p = {k: v for k, v in poly_mul(p, x).items() if k[0] + k[1] <= 7}
    return p


def to_sing(p):
    if not p:
        return '0'
    terms = []
    for (i, j, e) in sorted(p):
        mon = [f'y1^{i}' if i else '', f'y2^{j}' if j else '', f'B^{e}' if e else '']
        mon = '*'.join(x for x in mon if x)
        terms.append(mon or '1')
    return '+'.join(terms)


def rows(m, h):
    out = []
    for a, b in itertools.product(range(4), repeat=2):
        if a + b > h - 1:
            continue
        tau = (h + 3 - a - b) // 4
        prod = poly_mul(xpow(0, a), xpow(1, b))
        for t in range(tau):
            row = []
            for u in range(m + 1):
                r = u - t
                row.append({k: v for k, v in prod.items() if k[0] + k[1] == r} if r >= 0 else {})
            out.append(((a, b, t), row))
    return out


def script(m, h):
    R = rows(m, h)
    ncol = m + 1
    lines = ['option(redSB);', 'ring r = 2, (y1, y2, B), dp;']
    # the row module of A, generated by the condition rows as vectors in r^(m+1)
    gens = []
    for _, row in R:
        gens.append('[' + ', '.join(to_sing(e) for e in row) + ']')
    lines.append(f'module N = {", ".join(gens)};' if gens else 'module N = [0];')
    lines += [
        'matrix A = transpose(matrix(N, ' + str(ncol) + ', ncols(N)));',  # rows = conditions, columns u = 0..m
        'module Z = syz(A);',
        'int i; int j; int found = 0;',
        # existence certificate: a syzygy whose last component is 1
        'for (i = 1; i <= ncols(Z); i++) { if (found == 0 && Z[i][' + str(ncol) + '] == 1) {',
        '  found = 1; for (j = 1; j <= ' + str(ncol) + '; j++) { print("EXIST " + string(j - 1) + " " + string(Z[i][j])); } } }',
        # nonexistence certificate: f e_m = sum_r lambda_r row_r with f free of B
        'module E = gen(' + str(ncol) + ');',
        'module I = intersect(N, E);',
        'for (i = 1; i <= ncols(I); i++) { if (found == 0 && I[i][' + str(ncol) + '] != 0 && diff(I[i][' + str(ncol) + '], B) == 0) {',
        '  found = 2; print("NONEX " + string(I[i][' + str(ncol) + ']));',
        '  matrix T = lift(N, module(I[i]));',
        '  for (j = 1; j <= nrows(T); j++) { print("LAMBDA " + string(j - 1) + " " + string(T[j, 1])); } } }',
        'if (found == 0) { print("NONE"); }',
        'quit;',
    ]
    return '\n'.join(lines) + '\n', R


def main():
    outdir = Path(sys.argv[1])
    mmax = int(sys.argv[2]) if len(sys.argv) > 2 else 7
    outdir.mkdir(parents=True, exist_ok=True)
    for m in range(1, mmax + 1):
        h0 = (m + 1) // 2
        for h in (h0, h0 + 1):
            text, R = script(m, h)
            sp = outdir / f'm{m}-h{h}.sing'
            sp.write_text(text)
            res = subprocess.run(['Singular', '-q', str(sp)], capture_output=True, text=True, check=True)
            (outdir / f'm{m}-h{h}.out').write_text(res.stdout)
            print(f'm={m} h={h} conditions={len(R)}', flush=True)
            print(res.stdout.strip(), flush=True)


if __name__ == '__main__':
    main()
