// Exact Nullstellensatz spaces of the functional unary PHP base with avoidance axioms (cycle 228).
//
// Base: N holes, N+1 rows, variables x_{ij}, over F_2: Boolean, functional (x_ij x_ij' = 0),
// column exclusion (x_ij x_i'j = 0) and row axioms rho_i = 1. Polynomials of degree <= B are kept in
// matching normal form (monomials = partial matchings of size <= B); the degree-B NS space I_B of
// the base is then spanned by the marginal relations x_T (1 + rho_i), |T| <= B-1, i not in rows(T).
// Axioms: Q_b = prod_{u<=h} (1 + lambda_{b,u}), lambda uniform affine forms in the x_{ij}.
// The tool adds, clause by clause, all multiples x_sigma Q_b with |sigma| <= B-h and reports the
// increment of dim (I_B + V_b), whether 1 lies in the span, and the number of pivots by the degree of
// their leading monomial (monomials are ordered by degree, so the partial sums through e give
// dim (I_B + V_b) cap P_{<=e}, the quantity compared with a run at degree e to detect a degree fall).
// Dense elimination over F_2.
//
// Forms: --forms uniform (default; every cell with probability 1/2) or --forms label (N a power of
// two: every row contributes the zero set of a uniform affine function of the binary hole label, the
// unary image of a bit-affine form; these forms span a space L of dimension 1+(N+1)(1+log N)).
// --spanall 1 (with h=2) adds, instead of random clauses, all multiples f g x_sigma, |sigma| <= B-2,
// f, g in a basis of L: the last histogram entry is then tau_B, the dimension of the top-degree
// projection of everything the clauses over L can reach, which bounds dim G_B - dim (G_B cap P_{<=B-1}).
// --spanall 2 (with B=3) takes the multipliers from the basis of L as well: the span is I_3 + L L L, the
// degree-three part of the subalgebra generated by the forms.
// --postsub 1 (label forms, B=3): after the last clause, adds all products of three basis forms and reports
// how many are new, that is dim (I_3 + L L L + G_3) - dim G_3 (zero iff the subalgebra part lies in G_3).
//
// Usage: hw_unary_ns_rank --holes N --deg B --h H --clauses M --seed S [--forms label] [--spanall 1] --out FILE.jsonl
#include <cstdint>
#include <string>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <array>
#include <unordered_map>
#include <random>
#include <algorithm>
#include <chrono>
using namespace std;
typedef uint64_t u64;
static int N, R, B, H, MCL; static unsigned long SEED;
static vector<vector<int>> mons;              // sorted cell ids
static unordered_map<u64,int> idx;
static int W;                                 // words per row
static u64 key(const vector<int>& c){ u64 k=c.size(); for(int x: c) k=k*128+ (u64)(x+1); return k; } // cells < 127
static vector<u64*> piv;                      // pivot rows by leading column
static long rankNow=0;
static bool compatible(const vector<int>& a, int cell){ // cell not conflicting with matching a (identical cell allowed)
  int i=cell/N, j=cell%N; for(int x: a){ if(x==cell) return true; if(x/N==i || x%N==j) return false; } return true; }
// multiply two monomials; returns index or -1 (zero) or -2 (degree above B)
static int mulmon(const vector<int>& a, const vector<int>& b){
  vector<int> c=a; for(int x: b){ bool same=false; for(int y: c) if(y==x){same=true;break;} if(same) continue;
    int i=x/N,j=x%N; for(int y: c) if(y/N==i||y%N==j) return -1; c.push_back(x);} 
  if((int)c.size()>B) return -2; sort(c.begin(),c.end()); auto it=idx.find(key(c)); return it==idx.end()?-1:it->second; }
static bool addrow(u64* v){ // reduce; if nonzero, store as pivot (takes ownership of a copy)
  for(int w=W-1; w>=0; --w){ while(v[w]){ int bit=63-__builtin_clzll(v[w]); int col=w*64+bit; u64* p=piv[col];
      if(!p){ u64* q=(u64*)malloc(sizeof(u64)*W); memcpy(q,v,sizeof(u64)*W); piv[col]=q; ++rankNow; return true; }
      for(int t=0;t<=w;++t) v[t]^=p[t]; } }
  return false; }
static bool inspan(const u64* v0){ vector<u64> v(v0,v0+W); for(int w=W-1; w>=0; --w){ while(v[w]){ int bit=63-__builtin_clzll(v[w]); u64* p=piv[w*64+bit]; if(!p) return false; for(int t=0;t<=w;++t) v[t]^=p[t]; } } return true; }
int main(int argc,char**argv){ N=7;B=4;H=2;MCL=20;SEED=1; bool LABEL=false, SPANALL=false, SUBALG=false, POSTSUB=false;
  for(int a=1;a+1<argc;a+=2){ string s=argv[a]; long val=atol(argv[a+1]);
    if(s=="--out"){ if(!freopen(argv[a+1],"w",stdout)){ perror("out"); return 1; } continue; }
    if(s=="--forms"){ LABEL=(string(argv[a+1])=="label"); continue; }
    if(s=="--postsub"){ POSTSUB=val!=0; continue; }
    if(s=="--spanall"){ SPANALL=val!=0; SUBALG=val==2; continue; }
    if(s=="--holes")N=val; else if(s=="--deg")B=val; else if(s=="--h")H=val; else if(s=="--clauses")MCL=val; else if(s=="--seed")SEED=val; }
  R=N+1; auto t0=chrono::steady_clock::now(); int LOGN=0; while((1<<LOGN)<N) ++LOGN;
  if(LABEL && (1<<LOGN)!=N){ fprintf(stderr,"label forms need a power of two\n"); return 1; }
  if(R*N>126 || B>8){ fprintf(stderr,"board too large for the monomial key\n"); return 1; }
  // enumerate matchings of size <= B, ordered by size then lexicographically (higher degree = higher column)
  vector<int> cur; mons.push_back({});
  { vector<vector<int>> level={{}}; for(int s=1;s<=B;++s){ vector<vector<int>> nxt; for(auto&m: level){ int start=m.empty()?0:m.back()+1;
        for(int c=start;c<R*N;++c){ int i=c/N,j=c%N; bool ok=true; for(int y: m) if(y/N==i||y%N==j){ok=false;break;} if(ok){ auto m2=m; m2.push_back(c); nxt.push_back(m2);} } }
      for(auto&m: nxt) mons.push_back(m); level.swap(nxt);} }
  int U=mons.size(); for(int k=0;k<U;++k) idx[key(mons[k])]=k; W=(U+63)/64; piv.assign((size_t)W*64,nullptr);
  vector<long> ucount(B+1,0); for(auto&m: mons) ucount[m.size()]++;
  vector<u64> v(W);
  // marginal relations
  long nrel=0; for(int k=0;k<U;++k){ const auto&T=mons[k]; if((int)T.size()>B-1) continue; for(int i=0;i<R;++i){ bool used=false; for(int y: T) if(y/N==i) used=true; if(used) continue;
      fill(v.begin(),v.end(),0); v[k/64]^=1ULL<<(k%64); for(int j=0;j<N;++j){ int c=i*N+j; bool ok=true; for(int y: T) if(y%N==j) ok=false; if(!ok) continue; vector<int> m2=T; m2.push_back(c); sort(m2.begin(),m2.end()); int q=idx[key(m2)]; v[q/64]^=1ULL<<(q%64);} addrow(v.data()); ++nrel; } }
  long rankI=rankNow; vector<u64> one(W,0); one[0]=1; // monomial 0 is the empty matching
  { vector<long> byDeg(B+1,0); for(int c=0;c<U;++c) if(piv[c]) byDeg[mons[c].size()]++;
    printf("{\"base_pivots_by_leading_degree\":["); for(int e=0;e<=B;++e) printf("%ld%s",byDeg[e],e<B?",":""); printf("],\"monomials_by_degree\":["); for(int e=0;e<=B;++e) printf("%ld%s",ucount[e],e<B?",":""); printf("]}\n"); }
  double t1=chrono::duration<double>(chrono::steady_clock::now()-t0).count();
  printf("{\"holes\":%d,\"deg\":%d,\"h\":%d,\"monomials\":%d,\"relations\":%ld,\"rank_I\":%ld,\"quotient_dim\":%ld,\"one_in_I\":%s,\"seconds\":%.1f}\n",N,B,H,U,nrel,rankI,(long)U-rankI,inspan(one.data())?"true":"false",t1); fflush(stdout);
  mt19937_64 rng(SEED);
  if(SPANALL){ // basis of the form space: constant, and per row the row sum and the bit sets (label) or the cells (uniform)
    if(H!=2){ fprintf(stderr,"spanall needs h=2\n"); return 1; }
    vector<vector<int>> basis; basis.push_back({}); vector<int> isconst={1};
    for(int i=0;i<R;++i){ if(LABEL){ vector<int> all; for(int j=0;j<N;++j) all.push_back(i*N+j); basis.push_back(all); isconst.push_back(0);
        for(int a2=0;a2<LOGN;++a2){ vector<int> cs; for(int j=0;j<N;++j) if((j>>a2)&1) cs.push_back(i*N+j); basis.push_back(cs); isconst.push_back(0);} }
      else for(int j=0;j<N;++j){ basis.push_back({i*N+j}); isconst.push_back(0);} }
    auto formpoly=[&](int f){ vector<int> P; if(isconst[f]) P.push_back(0); else for(int c: basis[f]){ vector<int> m={c}; P.push_back(idx[key(m)]); } return P; };
    long mult=0; for(size_t f=0;f<basis.size();++f) for(size_t g=f;g<basis.size();++g){ auto Pf=formpoly(f), Pg=formpoly(g); unordered_map<int,int> acc;
        for(int x: Pf) for(int y: Pg){ int q=mulmon(mons[x],mons[y]); if(q>=0) acc[q]^=1; } vector<int> Q; for(auto&kv: acc) if(kv.second) Q.push_back(kv.first);
        if(SUBALG){ for(size_t k2=0;k2<basis.size();++k2){ auto Pk=formpoly(k2); fill(v.begin(),v.end(),0); for(int x: Pk) for(int p2: Q){ int q=mulmon(mons[x],mons[p2]); if(q>=0) v[q/64]^=1ULL<<(q%64); } addrow(v.data()); ++mult; } continue; }
        for(int k=0;k<U;++k){ if((int)mons[k].size()>B-2) continue; fill(v.begin(),v.end(),0); for(int p2: Q){ int q=mulmon(mons[k],mons[p2]); if(q>=0) v[q/64]^=1ULL<<(q%64); } addrow(v.data()); ++mult; } }
    vector<long> byDeg(B+1,0); for(int c=0;c<U;++c) if(piv[c]) byDeg[mons[c].size()]++;
    printf("{\"spanall\":true,\"forms\":\"%s\",\"basis\":%zu,\"multiples\":%ld,\"pivots_by_leading_degree\":[",LABEL?"label":"uniform",basis.size(),mult); for(int e=0;e<=B;++e) printf("%ld%s",byDeg[e],e<B?",":"");
    printf("],\"dim_span\":%ld,\"seconds\":%.1f}\n",rankNow,chrono::duration<double>(chrono::steady_clock::now()-t0).count()); return 0; }
  for(int b=1;b<=MCL;++b){ // random clause
    vector<int> Q={0}; // polynomial as sorted list of monomial indices with parity; start with 1
    auto polymul_affine=[&](const vector<int>& P, const vector<int>& cells, int cst){ unordered_map<int,int> acc; for(int p: P){ if(cst) acc[p]^=1; for(int c: cells){ int q=mulmon(mons[p],{c}); if(q>=0) acc[q]^=1; } } vector<int> out; for(auto&kv: acc) if(kv.second) out.push_back(kv.first); sort(out.begin(),out.end()); return out; };
    for(int u=0;u<H;++u){ vector<int> cells;
      if(LABEL){ for(int i=0;i<R;++i){ unsigned a=rng()&((2u<<LOGN)-1); for(int j=0;j<N;++j){ int val=(a>>LOGN)&1; for(int t=0;t<LOGN;++t) val^=((a>>t)&1)&((j>>t)&1); if(!val) cells.push_back(i*N+j); } } }
      else for(int c=0;c<R*N;++c) if(rng()&1) cells.push_back(c);
      int cst=(rng()&1)?0:1; // 1+lambda has constant 1+const(lambda)
      Q=polymul_affine(Q,cells,cst); }
    long before=rankNow; long mult=0;
    for(int k=0;k<U;++k){ if((int)mons[k].size()>B-H) continue; fill(v.begin(),v.end(),0); for(int p: Q){ int q=mulmon(mons[k],mons[p]); if(q>=0) v[q/64]^=1ULL<<(q%64); } addrow(v.data()); ++mult; }
    bool tip=inspan(one.data()); double t=chrono::duration<double>(chrono::steady_clock::now()-t0).count();
    { // pivots by degree of the leading monomial: dim of (I_B + V_b) cap P_{<=e} is the partial sum through e
      vector<long> byDeg(B+1,0); for(int c=0;c<U;++c) if(piv[c]) byDeg[mons[c].size()]++;
      printf("{\"clause\":%d,\"pivots_by_leading_degree\":[",b); for(int e=0;e<=B;++e) printf("%ld%s",byDeg[e],e<B?",":""); printf("]}\n"); }
    printf("{\"clause\":%d,\"terms\":%zu,\"multiples\":%ld,\"increment\":%ld,\"dim_V_mod_I\":%ld,\"quotient_left\":%ld,\"one_in_span\":%s,\"seconds\":%.1f}\n",b,Q.size(),mult,rankNow-before,rankNow-rankI,(long)U-rankNow,tip?"true":"false",t); fflush(stdout);
    if(tip) break; }
  if(POSTSUB && LABEL && B==3){ vector<vector<int>> basis; basis.push_back({});
    for(int i=0;i<R;++i){ vector<int> all; for(int j=0;j<N;++j) all.push_back(i*N+j); basis.push_back(all);
      for(int a2=0;a2<LOGN;++a2){ vector<int> cs; for(int j=0;j<N;++j) if((j>>a2)&1) cs.push_back(i*N+j); basis.push_back(cs);} }
    auto formpoly=[&](size_t f){ vector<int> P; if(f==0) P.push_back(0); else for(int c: basis[f]){ vector<int> m={c}; P.push_back(idx[key(m)]); } return P; };
    long before=rankNow; for(size_t f=0;f<basis.size();++f) for(size_t g=f;g<basis.size();++g) for(size_t k2=g;k2<basis.size();++k2){ auto Pf=formpoly(f),Pg=formpoly(g),Pk=formpoly(k2);
        unordered_map<int,int> acc; for(int x: Pf) for(int y: Pg){ int q=mulmon(mons[x],mons[y]); if(q>=0) acc[q]^=1; }
        fill(v.begin(),v.end(),0); for(auto&kv: acc) if(kv.second) for(int z: Pk){ int q=mulmon(mons[kv.first],mons[z]); if(q>=0) v[q/64]^=1ULL<<(q%64); } addrow(v.data()); }
    printf("{\"postsub\":true,\"subalgebra_dims_outside_G\":%ld}\n",rankNow-before); }
  return 0; }
