// Are non-Taylor classes generated by pairs? (entry-2026-09-27-pair-generation)
//
// Statement tested (hypothesis for random dense families, named in entry-2026-09-27-class-survival's next step):
// for M random dense tops tau_b = L_{b,0}^2 L_{b,1} on the square-free algebra S of N cells over F_3 (one row), the
// top syzygies of multiplier degree e are spanned by the Taylor span T and the syzygies of the pairs {b, c}
// (syzygies of the whole family supported on two slots).  The program reproduces the forms of
// pseudorandom_taylor_check (m = 1, same generator order), computes dim Syz, rank T, and the rank of T together with
// all pair syzygies (and, as a second level, all triple syzygies), exactly with FLINT nmod_mat.
// Usage: pair_generation_check OUT "N M seed e; ...".
#include <flint/nmod_mat.h>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <string>
#include <sstream>
#include <random>

typedef std::vector<std::pair<int, int>> Poly;
static int NN;
static std::vector<int> idx;
static std::vector<std::vector<int>> byDeg;

static Poly mul(const Poly& a, const Poly& b) {
    static std::vector<int> buf; if (buf.size() < (size_t)(1 << NN)) buf.assign(1 << NN, 0);
    std::vector<int> touched;
    for (auto& [ca, xa] : a) for (auto& [cb, xb] : b) if (!(ca & cb)) {
        int c = ca | cb; if (!buf[c]) touched.push_back(c);
        buf[c] = (buf[c] + xa * xb) % 3; if (!buf[c]) buf[c] = 3;
    }
    Poly out; for (int c : touched) { int v = buf[c] % 3; if (v) out.push_back({c, v}); buf[c] = 0; }
    return out;
}

// basis (as rows of length M*ne) of the syzygies supported on the slots in `slots`
static std::vector<std::vector<long>> subSyz(const std::vector<Poly>& tops, const std::vector<int>& slots, int e, long M) {
    long ne = byDeg[e].size(), ns = byDeg[e + 3].size(), k = slots.size();
    nmod_mat_t A; nmod_mat_init(A, ns, k * ne, 3);
    for (long s = 0; s < k; s++) for (long r = 0; r < ne; r++) for (auto& [c, x] : tops[slots[s]]) {
        int m = byDeg[e][r]; if (m & c) continue; long row = idx[m | c];
        nmod_mat_entry(A, row, s * ne + r) = (nmod_mat_entry(A, row, s * ne + r) + x) % 3;
    }
    nmod_mat_t K; nmod_mat_init(K, k * ne, k * ne, 3);
    long nul = nmod_mat_nullspace(K, A);
    std::vector<std::vector<long>> out(nul, std::vector<long>(M * ne, 0));
    for (long j = 0; j < nul; j++) for (long s = 0; s < k; s++) for (long r = 0; r < ne; r++) out[j][slots[s] * ne + r] = nmod_mat_entry(K, s * ne + r, j);
    nmod_mat_clear(A); nmod_mat_clear(K);
    return out;
}

static long rankRows(const std::vector<std::vector<long>>& rows, long cols) {
    if (rows.empty()) return 0;
    nmod_mat_t M; nmod_mat_init(M, rows.size(), cols, 3);
    for (size_t i = 0; i < rows.size(); i++) for (long j = 0; j < cols; j++) nmod_mat_entry(M, i, j) = rows[i][j];
    long r = nmod_mat_rank(M); nmod_mat_clear(M); return r;
}

int main(int argc, char** argv) {
    if (argc < 3) { fprintf(stderr, "usage: %s OUT CASES\n", argv[0]); return 2; }
    FILE* out = fopen(argv[1], "w");
    std::stringstream all(argv[2]); std::string item;
    while (std::getline(all, item, ';')) {
        std::stringstream ss(item); int N, M, e; unsigned seed;
        if (!(ss >> N >> M >> seed >> e)) continue;
        NN = N; int total = 1 << N; idx.assign(total, 0); byDeg.assign(N + 1, {});
        for (int c = 0; c < total; c++) { int d = __builtin_popcount(c); idx[c] = byDeg[d].size(); byDeg[d].push_back(c); }
        std::mt19937 rng(seed);
        std::vector<Poly> L0(M), L1(M), tops(M);
        for (int b = 0; b < M; b++) for (int w = 0; w < 2; w++) for (int col = 0; col < N; col++) {
            int v = rng() % 3; if (v) (w ? L1[b] : L0[b]).push_back({1 << col, v});
        }
        for (int b = 0; b < M; b++) tops[b] = mul(mul(L0[b], L0[b]), L1[b]);
        long ne = byDeg[e].size(), cols = (long)M * ne;
        std::vector<int> allSlots(M); for (int b = 0; b < M; b++) allSlots[b] = b;
        long dimSyz = subSyz(tops, allSlots, e, M).size();
        // Taylor generators
        std::vector<std::vector<long>> T;
        auto addTo = [&](std::vector<long>& v, int slot, const Poly& p, int sign) { for (auto& [c, x] : p) v[slot * ne + idx[c]] = ((v[slot * ne + idx[c]] + sign * x) % 3 + 3) % 3; };
        for (int b = 0; b < M; b++) {
            Poly B2 = mul(L1[b], L1[b]);
            if (e >= 1) for (int x : byDeg[e - 1]) { std::vector<long> v(cols, 0); addTo(v, b, mul(L0[b], {{x, 1}}), 1); T.push_back(v); }
            if (e >= 2) for (int x : byDeg[e - 2]) { std::vector<long> v(cols, 0); addTo(v, b, mul(B2, {{x, 1}}), 1); T.push_back(v); }
        }
        if (e >= 3) for (int b = 0; b < M; b++) for (int c = b + 1; c < M; c++) for (int x : byDeg[e - 3]) {
            std::vector<long> v(cols, 0); addTo(v, b, mul(tops[c], {{x, 1}}), 1); addTo(v, c, mul(tops[b], {{x, 1}}), -1); T.push_back(v);
        }
        long rkT = rankRows(T, cols);
        std::vector<std::vector<long>> TP = T;
        for (int b = 0; b < M; b++) for (int c = b + 1; c < M; c++) { auto s = subSyz(tops, {b, c}, e, M); TP.insert(TP.end(), s.begin(), s.end()); }
        long rkTP = rankRows(TP, cols);
        long rkTPT = -1;
        if (M >= 4) {
            std::vector<std::vector<long>> TPT = T;
            for (int a = 0; a < M; a++) for (int b = a + 1; b < M; b++) for (int c = b + 1; c < M; c++) { auto s = subSyz(tops, {a, b, c}, e, M); TPT.insert(TPT.end(), s.begin(), s.end()); }
            rkTPT = rankRows(TPT, cols);
        }
        fprintf(out, "{\"N\": %d, \"M\": %d, \"seed\": %u, \"e\": %d, \"dim_syz\": %ld, \"rank_taylor\": %ld, \"defect\": %ld, "
                     "\"rank_taylor_plus_pairs\": %ld, \"rank_taylor_plus_triples\": %ld}\n", N, M, seed, e, dimSyz, rkT, dimSyz - rkT, rkTP, rkTPT);
        fflush(out);
        printf("N=%d M=%d seed=%u e=%d: defect %ld, beyond pairs %ld, beyond triples %ld\n", N, M, seed, e, dimSyz - rkT, dimSyz - rkTP, rkTPT < 0 ? -1 : dimSyz - rkTPT);
        fflush(stdout);
    }
    fclose(out);
    return 0;
}
