-- Relation resolvents (entry-2026-09-27-relation-resolvents).
--
-- Tested statement.  For three clauses C_i = (1 - A_i^2) B_i with A_1 + A_2 + A_3 = 0, the relation syzygy of
-- prop:relation-length-syzygy falls to the resolvent R = B_1 B_2 B_3 (A_1 - A_2) (a consequence of the clauses, degree 4).
-- After adding R, is the family's top syzygy module, in the truncated algebra T_V of the span, generated by Frobenius
-- syzygies, Koszul pairs of tops without common factors, and the pair syzygies (lcm/tau_i) e_i - (lcm/tau_j) e_j of
-- tops sharing a factor, as thm:resolvent-taylor-glue's Taylor condition asks?  Control: the same without R
-- (defect expected at degree 6).  Output: per family, the first degree with a defect and the defect dimensions.
-- Usage: M2 --script relation_resolvent_check.m2 OUT
out := scriptCommandLine#1;
f := openOut out;
kk := ZZ/3;
S := kk[a1,b1,a2,b2,b3];
R := S / ideal(a1^3, b1^3, a2^3, b2^3, b3^3);
use R;
a3 := -(a1 + a2);
-- tops as lists of linear factors with exponents
tops0 := { {{a1,2},{b1,1}}, {{a2,2},{b2,1}}, {{a3,2},{b3,1}} };
rho := { {{b1,1},{b2,1},{b3,1},{a1 - a2,1}} };
prodTop := t -> product apply(t, fe -> (fe#0)^(fe#1));
run1 := (label, tops) -> (
    r := #tops;
    t := apply(tops, prodTop);
    F := R^(apply(t, x -> -(first degree x)));
    K := kernel map(R^1, F, matrix{t});
    unit := (i, c) -> apply(r, k -> if k == i then c else 0_R);
    gens0 := {};
    for i from 0 to r-1 do for fe in tops#i do gens0 = gens0 | {unit(i, (fe#0)^(3 - fe#1))};
    for i from 0 to r-1 do for j from i+1 to r-1 do (
        -- gcd of the two tops over shared factors (same form up to scalar; exponents min)
        g := 1_R;
        for fe in tops#i do for fe2 in tops#j do (
            M := matrix{{fe#0, fe2#0}};
            if rank (coefficients M)#1 == 1 then g = g * (fe#0)^(min(fe#1, fe2#1)));
        -- pair syzygy (tau_j / g) e_i - (tau_i / g) e_j, the Koszul pair when g = 1
        qi := (t#j) // g; qj := (t#i) // g;
        if qi * g != t#j or qj * g != t#i then error "division";
        gens0 = gens0 | {apply(r, k -> if k == i then qi else if k == j then -qj else 0_R)});
    Tay := image map(F, , transpose matrix gens0);
    ds := select(toList(0..16), d -> hilbertFunction(d, K) != hilbertFunction(d, Tay));
    dims := apply(ds, d -> hilbertFunction(d, K) - hilbertFunction(d, Tay));
    f << "{\"family\": \"" << label << "\", \"tops\": " << r << ", \"defect_degrees\": [" << concatenate between(", ", apply(ds, toString))
      << "], \"defect_dims\": [" << concatenate between(", ", apply(dims, toString)) << "]}" << endl;
    );
run1("three tops, relation A1+A2+A3=0 (control)", tops0);
run1("three tops plus resolvent B1B2B3(A1-A2)", tops0 | rho);
close f;
