-- Coarse certificate for the graded form of conj:global-tensor-falls. Tensor family c = 2, m = 3 (forms w . y and
-- w . z, y = (y_1, y_2, y_3), z = (y_4, y_5, y_6)); lifted family c = 3 adds the form y_0 (the space Z). A clause set
-- of proper span lies in the span E_l of the members on a line l of PG(2,3): E_l = l (x) F_3^2 (plus Z when lifted).
-- Its closed members' leading forms lie in the degree-d part of the subalgebra generated by E_l, d = 2c-1. Question:
-- is the leading form phi of the clause sum outside the sum over the 13 lines of these local pieces G_d(E_l)? If so,
-- a functional on G_d(E) killing every G_d(E_l) certifies graded non-absorption for all closed members at once.
-- Prints the rank of the sum of the local pieces, dim G_d(E), and whether phi (two seeds) lies in the sum.
kk = ZZ/3;
projPts = m -> (L := {}; scan(3^m, t -> (v := apply(m, i -> (t // 3^i) % 3);
  nz := select(m, i -> v#i != 0); if #nz > 0 and v#(first nz) == 1 then L = append(L, v))); L);
randNZ = () -> (x := 0_kk; while x == 0 do x = random kk; x);
pts3 = projPts 3;
lines3 = unique apply(subsets(#pts3, 2), pr -> (a := pts3#(pr#0); b := pts3#(pr#1);
  sort select(#pts3, i -> (M := matrix(kk, {a, b, pts3#i}); rank M == 2))));
certTest = (lifted, seeds) -> (
  c := if lifted then 3 else 2; d := 2 * c - 1;
  r := if lifted then 7 else 6; off := if lifted then 1 else 0;
  R := kk[x_1..x_r];
  A := R/ideal(apply(gens R, v -> v^3));
  Q := R/ideal(apply(gens R, v -> v^3 - v));
  xi := (w, T) -> sum(3, i -> w#i * T_(off + i));
  ze := (w, T) -> sum(3, i -> w#i * T_(off + 3 + i));
  B := basis(d, A);
  -- local pieces: products of d forms from E_l, via monomials in a basis of E_l
  pieces := apply(lines3, l -> (a := pts3#(l#0); b := pts3#(l#1);
    El := {xi(a, A), xi(b, A), ze(a, A), ze(b, A)} | (if lifted then {A_0} else {});
    S := kk[e_1..e_(#El)]; T := S/ideal(apply(gens S, v -> v^3));
    f := map(A, S, El);
    lift(last coefficients(matrix{apply(flatten entries basis(d, T), mm -> f(lift(mm, S)))}, Monomials => B), kk)));
  Lsum := fold(pieces, (u, v) -> u | v);
  rL := rank Lsum;
  outs := apply(seeds, s -> (setRandomSeed s;
    F := sum(pts3, w -> (a1 := random kk; a2 := random kk; b0 := random kk;
      if lifted then (M := random(kk^2, kk^3); while rank M_{0, 1} < 2 do M = random(kk^2, kk^3);
        fs := {Q_0 + b0, xi(w, Q) + a1, ze(w, Q) + a2};
        P1 := sum(3, j -> M_(0, j) * fs#j); P2 := sum(3, j -> M_(1, j) * fs#j);
        (1 - (fs#2)^2) * P1^2 * P2^2)
      else (s0 := randNZ(); t0 := random kk; P := s0 * (xi(w, Q) + a1) + t0 * (ze(w, Q) + a2);
        (1 - (ze(w, Q) + a2)^2) * P^2)));
    g := lift(F, R);
    phi := sum(select(terms g, t -> first degree t == d), t -> sub(t, A));
    pv := lift(last coefficients(matrix{{phi}}, Monomials => B), kk);
    (first degree g, pv == 0, rank(Lsum | pv) == rL)));
  print("lifted=" | toString lifted | " c=" | toString c | " d=" | toString d | ": dim G_d(E)=" | toString numColumns B |
    " rank of the sum of the 13 local pieces=" | toString rL | "; per seed (deg F, phi zero, phi in the sum): " | toString outs));
certTest(false, {1, 2});
certTest(true, {1, 2});
exit 0
